//
//  myfs-structs.h
//  myfs
//
//  Created by Oliver Waldhorst on 07.09.17.
//  Copyright © 2017 Oliver Waldhorst. All rights reserved.
//
#include <math.h>

#ifndef myfs_structs_h
#define myfs_structs_h

#define NAME_LENGTH 255
#define BLOCK_SIZE 512
#define NUM_DIR_ENTRIES 64
#define NUM_OPEN_FILES 64

// TODO: Add structures of your file system here
#define NUM_SUPER_BLOCKS  1
#define NUM_DMAP_BLOCKS 16
#define NUM_FAT_BLOCKS 256
#define NUM_ROOT_BLOCKS NUM_DIR_ENTRIES + 2
#define NUM_DATA_BLOCKS 65536

#define START_SUPER_BLOCKS 0
#define START_DMAP_BLOCKS START_SUPER_BLOCKS + NUM_SUPER_BLOCKS
#define START_FAT_BLOCKS START_DMAP_BLOCKS + NUM_DMAP_BLOCKS
#define START_ROOT_BLOCKS START_FAT_BLOCKS + NUM_FAT_BLOCKS
#define START_DATA_BLOCKS START_ROOT_BLOCKS + NUM_ROOT_BLOCKS

//SBLOCK
#define NUM_NAME_FILESYSTEM_BITS 4 * 8
#define NUM_RESERVED_ENTRIES_BITS 7
#define NUM_RESERVED_BLOCKS_BITS 17
#define NUM_RESERVED_DATA_BYTES_BITS 25 * 8 + 1

#define START_NAME_FILESYSTEM_BITS 0
#define START_RESERVED_ENTRIES_BITS START_NAME_FILESYSTEM_BITS + NUM_NAME_FILESYSTEM_BITS
#define START_RESERVED_BLOCKS_BITS START_RESERVED_ENTRIES_BITS + NUM_RESERVED_ENTRIES_BITS
#define START_RESERVED_DATA_BYTES_BITS START_RESERVED_BLOCKS_BITS + NUM_RESERVED_BLOCKS_BITS

//FAT
#define ADRESS_LENGTH_BITS 16
#define NUM_ADRESS_PER_BLOCK 512 / 2

//ROOT
#define NUM_FILENAME_BITS NAME_LENGTH * 8
#define NUM_FILE_SIZE_BITS 25 * 8 + 1
#define NUM_USERID_BITS 8
#define NUM_GROUPID_BITS 8
#define NUM_ACCESS_RIGHT_BITS 10
#define NUM_TIMESTAMP_BITS 6 * 8
#define NUM_POINTER_BITS 2 * 8

#define START_FILENAME_BITS 0
#define START_FILE_SIZE_BITS  START_FILENAME_BITS +  NUM_FILENAME_BITS
#define START_USERID_BITS START_FILE_SIZE_BITS + NUM_FILE_SIZE_BITS
#define START_GROUPID_BITS START_USERID_BITS + NUM_USERID_BITS
#define START_ACCESS_RIGHT_BITS START_GROUPID_BITS + NUM_GROUPID_BITS
#define START_FIRST_TIMESTAMP_BITS START_ACCESS_RIGHT_BITS + NUM_ACCESS_RIGHT_BITS
#define START_SECOND_TIMESTAMP_BITS START_FIRST_TIMESTAMP_BITS + NUM_TIMESTAMP_BITS
#define START_THIRD_TIMESTAMP_BITS START_SECOND_TIMESTAMP_BITS + NUM_TIMESTAMP_BITS
#define START_POINTER_BITS START_THIRD_TIMESTAMP_BITS + NUM_TIMESTAMP_BITS


#endif /* myfs_structs_h */
